name: Deploy DayDraft to Pages

on:
  push: 
    branches: ["main"]
  workflow_dispatch: {} # allow manually triggering workflow

permissions: 
  contents: read
  pages: write
  id-token: write

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Build Project
        run: deno task build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4